# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-service-yrkande
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

quarkus.test.integration-test-name-pattern=.*IT

%dev.handlaggning.api.base-url=http://localhost:8080
handlaggning.api.base-url=http://rimfrost-k8s-handlaggning:8080
